IP = "192.168.1.90"
USER = "admin"
PASS = "admin"
ONVIF_PORT = 8899
RTSP_PORT = "554"
STREAM_PATH = "live/ch0"
RTSP_URL = f"rtsp://{USER}:{PASS}@{IP}:{RTSP_PORT}/{STREAM_PATH}"
MOVE_SPEED = 0.5
# --- Camera Physical Limits ---
MIN_ANGLE = -170.0              
MAX_ANGLE = 170.0               
PAN_RANGE_SOFTWARE = 350.0       

TIME_PER_DEGREE = 0.0749

MIN_TILT = 5.0
MAX_TILT = 45.0
TILT_RANGE_SOFTWARE = 85.0
TILT_TIME_END_TO_END = 7.0
TIME_PER_DEGREE_TILT = TILT_TIME_END_TO_END / TILT_RANGE_SOFTWARE
